import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { rethinkSans, ballingerMono } from "../fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Eloquent Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rethinkSans.variable} ${ballingerMono.variable}`}
    >
      <body>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
